kind: pipeline
type: digitalocean
name: default

token:
  from_secret: token

server:
  image: docker-20-04
  size: s-1vcpu-1gb
  region: nyc1

steps:
  - name: login to docker hub
    environment:
      token:
        from_secret: token
    commands:
      - docker login registry.digitalocean.com -u rohit@cloudtix.in -p $token

  - name: Build docker image
    commands:
      - docker build -t registry.digitalocean.com/gitcommits:${DRONE_COMMIT_SHA:0:10} .
      - docker images
    depends_on:
      - login to docker hub

  - name: Install slim tool kit
    commands:
      - curl -sL https://raw.githubusercontent.com/slimtoolkit/slim/master/scripts/install-slim.sh | sudo -E bash -
    depends_on:
      - Build docker image

  - name: use slim and compress image
    commands:
      - slim build --env "MONGO_URL=mongodb+srv://myAtlasDBUser:Rohit2023@github-webhook.p0pdz5y.mongodb.net/?retryWrites=true&w=majority&appName=Github-Webhook" registry.digitalocean.com/gitcommits:${DRONE_COMMIT_SHA:0:10}
    depends_on:
      - Install slim tool kit

  - name: rename image
    commands:
      - docker tag registry.digitalocean.com/gitcommits.slim:latest registry.digitalocean.com/gitcommits:${DRONE_COMMIT_SHA:0:10}
      - docker tag registry.digitalocean.com/gitcommits.slim:latest registry.digitalocean.com/gitcommits:latest
    depends_on:
      - use slim and compress image

  - name: docker image push
    commands:
      - docker push registry.digitalocean.com/gitcommits/test:latest
      - docker push registry.digitalocean.com/gitcommits/test:{$DRONE_COMMIT_SHA:0:10}
    depends_on:
      - rename image

trigger:
  event:
    - push
    - tag
  branch:
    - main
