apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  labels:
    app: webhook
  namespace: webhook-ki-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
        - name: webhook
          image: rohitdarekar816/gitcommits:latest
          ports:
            - containerPort: 5004
          env:
            - name: MONGO_URL
              value: "mongodb+srv://myAtlasDBUser:Rohit2023@github-webhook.p0pdz5y.mongodb.net/?retryWrites=true&w=majority&appName=Github-Webhook"
