apiVersion: v1
kind: Service
metadata:
  name: webhook-ki-service
  namespace: webhook-ki-deployment
spec:
  selector:
    matchLabels:
      app: webhook
  ports:
    - name: http
      protocol: TCP
      port: 5004
      targetPort: 5004
